from src.constants import (
    PATH_MODEL_1_CONTACT,
    PATH_MODEL,
)

MODEL_PATHS = (PATH_MODEL_1_CONTACT, PATH_MODEL, PATH_MODEL, PATH_MODEL, PATH_MODEL_1_CONTACT)
PHASE_TIME = (0.4, 0.2, 0.3, 0.3, 1)
N_SHOOTING = (40, 20, 30, 30, 40)